# Monorepo #####################################################################

monorepo_root = true
[monorepo]
config_roots = ["pkgs/*"]

[tools]


# Stack ########################################################################

# Node.js

node = "lts"
pnpm = "latest"

# Tools
cargo-binstall = "latest" # Install cargo binaries


# Settings #####################################################################

[settings]
lockfile = true
idiomatic_version_file_enable_tools = ["rust"] # Use rust-toolchain.toml


# Tasks ########################################################################


# Install ======================================================================

# install ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[tasks.install]
depends = ["install/pnpm"]

# install:pnpm ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[tasks."install/pnpm"]
run = "pnpm install"


# Test =========================================================================

# test ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[tasks.test]
run = "cargo nextest run --no-tests pass"

# test:watch ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[tasks."test:watch"]
run = "bacon nextest"
