# Monorepo #####################################################################

monorepo_root = true
[monorepo]
config_roots = ["pkgs/*"]

[tools]


# Stack ########################################################################

# Node.js

node = "24"
pnpm = "latest"

# Tools
cargo-binstall = "latest" # Install cargo binaries


# Settings #####################################################################

[settings]
lockfile = true
idiomatic_version_file_enable_tools = ["rust"] # Use rust-toolchain.toml


# Tasks ########################################################################


# Install ======================================================================

# install ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[tasks.install]
depends = ["install/pnpm"]

# install:pnpm ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[tasks."install/pnpm"]
run = "pnpm install"


# Test =========================================================================

# test ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[tasks.test]
run = "cargo nextest run --no-tests pass"

# test:watch ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[tasks."test:watch"]
run = "bacon nextest"

# test/snapshots:review ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[tasks."test/snapshots:review"]
run = "cargo insta test --review"

# test/snapshots:approve ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[tasks."test/snapshots:approve"]
run = "cargo insta approve"


# Examples =====================================================================

# example ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[tasks.example]
usage = '''
arg "<example>" help="Example name"
'''
run = "cargo run --bin cssh -- run ./examples/{{usage.example}}.sh"

